version: '3.8'
services:
  mariadb:
    image: mariadb:10.10
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: userPw
      MYSQL_ROOT_PASSWORD: rootPw
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    restart: always

volumes:
  data:
