spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/example
    username: user
    password: userPw
mybatis:
  mapper-locations: classpath*:sqlmap/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
