version: '3.8'

services:
  mysql-workbench:
    image: mysql-workbench:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ./config:/config
    ports:
      - "3000:3000"
      - "3001:3001"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    platform: linux/amd64
