version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootPw"
      TZ: "Asia/Seoul"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
  mysql-workbench:
    image: mysql-workbench:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ./workbench/config:/config:shared
    ports:
      - "3000:3000"
      - "3001:3001"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    platform: linux/amd64

volumes:
  db-data: {}
