spring:
  flyway:
    locations:
      - classpath:db/migration
  profiles:
    default: local
logging:
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss"
--- # local
spring:
  config.activate.on-profile: local
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dummy
  datasource:
    url: jdbc:mariadb://localhost:3306/example
    username: user
    password: userPw
